//UserReducer
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOCATION = "USER_LOCATION";
export const AUTH_ERROR = "AUTH_ERROR";
export const USER_LOADED = "USER_LOADED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

//ModalReducer
export const MODAL_SHOW = "MODAL_SHOW";
export const MODAL_CLOSE = "MODAL_CLOSE";
export const POST_MODAL_SHOW = "POST_MODAL_SHOW";
export const POST_MODAL_CLOSE = "POST_MODAL_CLOSE";
export const INFO_MODAL_SHOW = "INFO_MODAL_SHOW";
export const INFO_MODAL_CLOSE = "INFO_MODAL_CLOSE";
export const SIGNIN_ON = "SIGNIN_ON";
export const SIGNIN_OFF = "SIGNIN_OFF";
export const MODAL_REGISTER_FAIL = "MODAL_REGISTER_FAIL";
export const MODAL_LOGIN_FAIL = "MODAL_LOGIN_FAIL";
export const MODAL_ALERT = "MODAL_ALERT";

//postReducer
export const POST_SUCCESS = "POST_SUCCESS";
export const POST_FAIL = "POST_FAIL";
export const NEW_MARKER_SUCCESS = "NEW_MARKER_SUCCESS";
export const RESET_NEW_MARKER = "RESET_NEW_MARKER";
export const CLEAR_ALL_POST = "CLEAR_ALL_POST";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAIL = "DELETE_POST_FAIL";

//getPostReducer
export const GETALLPOST_SUCCESS = "GETALLPOST_SUCCESS";
export const GETALLPOST_FAIL = "GETALLPOST_FAIL";
export const GETIMG_SUCCESS = "GETIMG_SUCCESS";
export const GETIMG_FAIL = "GETIMG_FAIL";
export const LOADING_POST_ON = "LOADING_POST_ON";
export const LOADING_POST_OFF = "LOADING_POST_OFF";
export const LOADING_IMG_ON = "LOADING_IMG_ON";
export const LOADING_IMG_OFF = "LOADING_IMG_OFF";

//windowReducer
export const WINDOW_OPEN = "WINDOW_OPEN";
export const WINDOW_CLOSE = "WINDOW_CLOSE";
export const POST_WINDOW_OPEN = "POST_WINDOW_OPEN";
export const POST_WINDOW_CLOSE = "POST_WINDOW_CLOSE";
export const SET_SELECTED_POST = "SET_SELECTED_POST";
export const OFF_SELECTED_POST = "OFF_SELECTED_POST";
